name: CI

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 5.3.0
          - 4.14.2

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add graphics.dev . --no-action
      - run: opam depext graphics --yes
      - run: opam install . --deps-only
      - run: opam exec -- dune build @install
      - run: opam exec -- dune runtest
